INSERT INTO UNICORN (name, type, rate, color, available, healthCheck) VALUES
    ('Joi Joyner', 'Gradlies', 32, 'Midnight Blue', FALSE, FALSE),
    ('Domitila Dahlman', 'Qhugale', 36, 'Plum', FALSE, TRUE),
    ('Carly Cohan', 'Gradlies', 46, 'Magenta', TRUE, TRUE),
    ('Tonisha Troia', 'Accapard', 3, 'Slate Gray', TRUE, TRUE),
    ('Paulina Ploof', 'Korserian', 80, 'Indian Red', FALSE, FALSE),
    ('Cherise Capoccia', 'Gradlies', 33, 'Orange Red', TRUE, TRUE),
    ('Lai Lance', 'Shellerine', 87, 'Aquamarine', TRUE, FALSE),
    ('Billye Barrientos', 'Qhugale', 50, 'Medium Aquamarine', FALSE, FALSE),
    ('Tyree Tugwell', 'Accapard', 32, 'Medium Blue', FALSE, FALSE),
    ('Mitchel Mickey', 'Shellerine', 8, 'Navy', TRUE, FALSE),
    ('Christa Crigger', 'Khalbat', 50, 'Tan', TRUE, TRUE),
    ('Ling Lindauer', 'Osthious', 37, 'Dark Sea Green', FALSE, FALSE),
    ('Werner Wherry', 'Llimovine', 62, 'Silver', FALSE, TRUE),
    ('Valda Varnadoe', 'Lalinean', 77, 'Dark Red', FALSE, FALSE),
    ('Ruthie Remick', 'Qhugale', 99, 'Medium Spring Green', FALSE, TRUE),
    ('Max Mao', 'Osthious', 69, 'Antique White', TRUE, FALSE),
    ('Sofia Slezak', 'Korserian', 36, 'Teal', FALSE, FALSE),
    ('Joni Junkin', 'Accapard', 27, 'Dark Gray', TRUE, FALSE),
    ('Aleta Amon', 'Llimovine', 10, 'Fuchsia', TRUE, TRUE),
    ('Lavinia Lowrie', 'Llimovine', 94, 'Yellow Green', TRUE, TRUE),
    ('Chelsea Chiu', 'Korserian', 33, 'Honeydew', TRUE, FALSE),
    ('Tawana Telles', 'Khalbat', 70, 'Light Sky Blue', TRUE, FALSE),
    ('Corina Cohrs', 'Ranmite', 98, 'Dark Salmon', TRUE, FALSE),
    ('Aaron Arguelles', 'Lalinean', 56, 'Aqua', TRUE, FALSE),
    ('Stacia Swearngin', 'Lalinean', 94, 'Dark Violet', FALSE, TRUE),
    ('Christinia Casazza', 'Shellerine', 27, 'Amethyst', TRUE, TRUE),
    ('Gerardo Gales', 'Korserian', 93, 'Dark Goldenrod', FALSE, FALSE),
    ('Shala Schoenrock', 'Llimovine', 52, 'Dark Slate Gray', FALSE, TRUE),
    ('Ethelyn Engen', 'Qhugale', 18, 'Light Sea Green', FALSE, FALSE),
    ('Jettie Jamison', 'Shellerine', 72, 'Dim Gray', TRUE, TRUE),
    ('Cayla Chichester', 'Ranmite', 79, 'Dark Cyan', TRUE, FALSE),
    ('Eleanor Eskridge', 'Ranmite', 46, 'Peach Puff', FALSE, TRUE),
    ('Christeen Cypert', 'Khalbat', 2, 'Lavender Blush', FALSE, FALSE),
    ('Marisol Mansell', 'Osthious', 56, 'Light Salmon', FALSE, TRUE),
    ('Arlinda Andresen', 'Lalinean', 1, 'Medium Slate Blue', TRUE, FALSE),
    ('Fran Faler', 'Ranmite', 61, 'Lime Green', TRUE, TRUE),
    ('Mica Mance', 'Shellerine', 16, 'Dark Turquoise', TRUE, FALSE),
    ('Mariano Mackin', 'Korserian', 94, 'Seashell', FALSE, TRUE),
    ('Ben Benning', 'Khalbat', 81, 'Wheat', FALSE, TRUE),
    ('Vernetta Veale', 'Llimovine', 4, 'Blue Violet', FALSE, TRUE),
    ('Gabrielle Gaetano', 'Lalinean', 17, 'Gainsboro', TRUE, TRUE),
    ('Noah Nobile', 'Accapard', 47, 'Navajo White', TRUE, FALSE),
    ('Carla Coover', 'Accapard', 7, 'Ghost White', TRUE, FALSE),
    ('Libby Lavery', 'Qhugale', 13, 'Sky Blue', TRUE, TRUE),
    ('Nestor Nickel', 'Ranmite', 21, 'Maroon', TRUE, TRUE),
    ('Dori Damore', 'Gradlies', 15, 'Royal Blue', TRUE, FALSE),
    ('Nia Nieto', 'Khalbat', 32, 'Dark Orange', FALSE, TRUE),
    ('Maureen Milian', 'Osthious', 75, 'Green', TRUE, FALSE),
    ('Bryon Breiner', 'Gradlies', 80, 'Medium Orchid', TRUE, TRUE),
    ('Tosha Turnbull', 'Osthious', 58, 'Moccasin', FALSE, FALSE)
;

INSERT INTO USER (userName, password) VALUES 
    ('123', '123');