-- Set timezone to GMT +08:00 (Kuala Lumpur / Singapore)
SET time_zone = '+08:00';

-- Drop database if database exists
DROP DATABASE IF EXISTS `UNICORNDB`;
CREATE DATABASE IF NOT EXISTS `UNICORNDB` CHARACTER SET utf8mb4;

-- Select database after it is created
USE CLUB-MAN;

-- Drop tables if table exists
SET FOREIGN_KEY_CHECKS = 0;
DROP TABLE IF EXISTS `UNICORN`;
DROP TABLE IF EXISTS `RENTAL`;
DROP TABLE IF EXISTS `CUSTOMER`;
DROP TABLE IF EXISTS `USER`;
SET FOREIGN_KEY_CHECKS = 1;

CREATE TABLE `UNICORN` (
    `unicornID` INTEGER AUTO_INCREMENT NOT NULL,
    `name` VARCHAR(20) NOT NULL,
    `type` VARCHAR(20) NOT NULL,
    `rate` DOUBLE NOT NULL,
    `color` VARCHAR(10) NOT NULL,
    `available` BOOLEAN NOT NULL,
    `healthCheck` BOOLEAN NOT NULL,
    `creation` TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    PRIMARY KEY (`unicornID`),
    UNIQUE (`unicornID`)
);

CREATE TABLE `RENTAL` (
    `rentalID` INTEGER AUTO_INCREMENT NOT NULL,
    `unicornID` INTEGER NOT NULL,
    `customerID` INTEGER NOT NULL,
    `start` LONG NOT NULL,
    `end` LONG NOT NULL,
    `depositPaid` DOUBLE NOT NULL,
    `payingPrice` DOUBLE NOT NULL,
    `returned` BOOLEAN NOT NULL,
    `userID` INTEGER NOT NULL,
    `creation` TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    PRIMARY KEY (`rentalID`)
);

CREATE TABLE `CUSTOMER` (
    `customerID` INTEGER AUTO_INCREMENT NOT NULL,
    `name` VARCHAR(20) NOT NULL,
    `phoneNo` VARCHAR(20) NOT NULL,
    `unicornLicenseID` VARCHAR(20) NOT NULL,
    `creation` TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    PRIMARY KEY (`customerID`)
);

CREATE TABLE `USER` (
    `userID` INTEGER AUTO_INCREMENT NOT NULL,
    `userName` VARCHAR(50) NOT NULL,
    `password` VARCHAR(50) NOT NULL,
    `creation` TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    PRIMARY KEY (`userID`)
);

ALTER TABLE `RENTAL` ADD FOREIGN KEY (`unicornID`) REFERENCES `UNICORN`(`unicornID`);
ALTER TABLE `RENTAL` ADD FOREIGN KEY (`customerID`) REFERENCES `CUSTOMER`(`customerID`);
ALTER TABLE `RENTAL` ADD FOREIGN KEY (`userID`) REFERENCES `USER`(`userID`);